### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ibab** [tensorprob/tensorprob#78]
Let's come up with a plan for how to proceed with development (So we can finally get a v0.1 out).
Here are some ideas I've been playing with:

- [ ] Rewrite the framework to interpret a *generative* graph (TensorFlow graph that samples random values and transforms them) as a probability density that we can condition on. For this, we can define a `tp.RegisterLogProbability` decorator that associates a log probability with each distribution. We can use the facilities that exist in TensorFlow for registering gradients and other functions. We should then write a function `total_log_probability` that traverses the graph in topological order and
  1. Instantiates the log probability if we're dealing with a distribution (sampling) operator
  2. Creates a copy if we're dealing with a non-distribution operator and connects it up
  3. Returns a new TensorFlow graph that represents the density we're looking for

At this stage, we should require that only distributions (and not transformations of distributions) can    be initialized/observed, which should make the code simple to write.

- [ ] Create a `tp.RegisterIntegral` decorator that will allow us to deal with bounded distributions and define integrals (== measures) for all distributions
 
- [ ] Add constrained variables like `Simplex`. These have a reverse transformation, coded as a TensorFlow expression. When the user supplies something like `x = [0.2, 0.3, 0.5]` in order to set a `Simplex`, we can use the reverse transformation to do `variable = tf.Variable(simplex_inv(x))`.
We can use this system as a hack until we properly support transformations of random variables (or just keep it if we decide that they aren't worth it)

- [ ] Add special support for mixture components. I'm thinking that mixture component can be interpreted as *sub-probability* distributions (distributions whose total probability sums to something less than 1). When building the total probability, we could build parallel sub-probability distributions for each component. I think this shouldn't be too difficult to implement.
For the mixture syntax, I'm thinking of
 ```python
 X = Mix2(theta, X1, X2, components=['signal', 'background'])
 ```
Where the user has to optionally supply the name of each mixture component. We then only build the component densities if the user has supplied names. After completing the model, they can then use
 ```python
 model.components['signal'].pdf(x, y, z)
 ```
to get the values for a specific component. (So `.components` simply returns all the sub-densities that we've built previously, possibly as a dictionary).
We can build the densities by zero-ing out the densities of all components that don't contain our specific random variable.

- [ ] optional: Turn TensorProb into a proper probabilistic programming language by supporting observing/setting transformations of random variables. In principle, any probabilistic program can be understood as a vector of random variables X with a total (combined) probability measure μ, and a function f that takes N parameters (number of entries in X) and has M outputs. If we want to be able to perform inference on the transformed random variables f(X), we can calculate the push-forward μ* as μ ∘ (preimage f), where preimage gets us the set of all values that produce a given output of f.
For example, the preimage of exp is log, the preimage of squaring is {sqrt(y), -sqrt(y)}, and so on.
We can get the total preimage by "running the computation backwards" and combining preimages where necessary. Maybe we can find a clever way to save work here, but I'm afraid that the code for this might be tricky. Still, because we probably don't want to support recursion and while loops, it should be possible to get exact results for this. The result would be pretty cool, allowing us to simplify the rest of the framework quite a bit and allowing things like `tf.select` `tf.greater`, `tf.floor` to work correctly in the generative model.
